dubbo:
  application:
    name: spring-boot-provider
    qos-enable: false
  registry:
    address: zookeeper://192.168.71.128:2181
  protocol:
    port: 21883
    name: dubbo
  config-center:
    address: zookeeper://192.168.71.128:2181
server:
  port: 8080
logging:
  file: provider.log
